### ISSUE TITLE
when i run  train_3d.py ,i will  get trouble 

### ISSUE THREAD

**Issue by imay99** [microsoft/voxelpose-pytorch#2]
发生异常: RuntimeError
Expected object of scalar type Float but got scalar type Double for argument #2 'other'
  File "/home/wu/voxelpose-pytorch/lib/models/project_layer.py", line 80, in get_voxel
    bounding[i, 0, 0, :, c] = (xy[:, 0] >= 0) & (xy[:, 1] >= 0) & (xy[:, 0] < width) & (xy[:, 1] < height)
  File "/home/wu/voxelpose-pytorch/lib/models/project_layer.py", line 107, in forward
    cubes, grids = self.get_voxel(heatmaps, meta, grid_size, grid_center, cube_size)
  File "/home/wu/voxelpose-pytorch/lib/models/cuboid_proposal_net.py", line 103, in forward
    self.grid_size, [self.grid_center], self.cube_size)
  File "/home/wu/voxelpose-pytorch/lib/models/multi_person_posenet.py", line 65, in forward
    root_cubes, grid_centers = self.root_net(all_heatmaps, meta)
  File "/home/wu/voxelpose-pytorch/lib/core/function.py", line 126, in validate_3d
    input_heatmaps=input_heatmap)
  File "/home/wu/voxelpose-pytorch/run/train_3d.py", line 135, in main
    precision = validate_3d(config, model, test_loader, final_output_dir)
  File "/home/wu/voxelpose-pytorch/run/train_3d.py", line 161, in <module>
    main()

**Comment by WuYue99** [comment]
the error in voxelpose-pytorch/lib/models/project_layer.py

**Comment by CHUNYUWANG** [comment]
@WuYue99 Try to upgrade Pytorch to 1.4.0

Or you can transform the data type to float using .float()

**Comment by zsw667291** [comment]
transform which data to flaot?

**Comment by sudo-vinnie** [comment]
Could someone help ?
I get the idea that the data is not being loaded ?

```
Traceback (most recent call last):
  File "run/train_3d.py", line 169, in <module>
    main()
  File "run/train_3d.py", line 92, in main
    pin_memory=True) #Error
  File "/home/chava/Kyutech/Anaconda/envs/VoxelPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/chava/Kyutech/Anaconda/envs/VoxelPose/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
