### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SnmallPudge** [microsoft/voxelpose-pytorch#31]
When I run  item on linux, it comes  this error. But  I can train on windows , I don't konw how to deal with this problem. THX
Traceback (most recent call last):
  File "run/train_3d.py", line 160, in <module>
    main()
  File "run/train_3d.py", line 133, in main
    train_3d(config, model, optimizer, train_loader, epoch, final_output_dir, writer_dict)
  File "/mnt/e/voxelpose-pytorch-main/run/../lib/core/function.py", line 44, in train_3d
    targets_3d=targets_3d[0])
IndexError: list index out of range

**Comment by Forest-Darkness** [comment]
Hello, I have encountered the same problem. How did you solve it

**Comment by turtlebot1** [comment]
I had that issue, it was because the 'hdImgs' folder in the panoptic dataset was missing. Basically the video which should be split into images.
